stages:
    - test
    - build
    - deploy

run_tests:
    image: python:3.8-alpine
    stage: test
   # before_script:
        #- sudo apt-get update && apt-get install pip
        #- /usr/local/bin/python -m pip install --upgrade pip
        
    script:
        - python3 test_cards.py

run_app:
    stage: build
    image: python:3.8-alpine
    before_script:
        - sudo apt-get update
        - sudo apt-get install ca-certificates 
        - sudo apt-get install ca-curl
        - sudo apt-get install ca-gnupg 
        - sudo apt-get install ca-lsb-release
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        - echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux ubuntu \$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        - docker pull osrf/ros:foxy-desktop
        
    script:
        - ros2 run cards_pypkg dealer
        - ros2 run cards_pypkg player

